using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Yumiko.LinqToHtml.Tags.Item.Scopes
{
    public sealed class Scopes
    {

        public readonly static Type Comment = typeof(Comment);
        public readonly static Type Doctype = typeof(Doctype);

        public readonly static Type A = typeof(A);
        public readonly static Type Abbr = typeof(Abbr);
        public readonly static Type Acronym = typeof(Acronym);
        public readonly static Type Address = typeof(Address);
        public readonly static Type Applet = typeof(Applet);
        public readonly static Type Area = typeof(Area);
        public readonly static Type Article = typeof(Article);
        public readonly static Type Aside = typeof(Aside);
        public readonly static Type Audio = typeof(Audio);
        public readonly static Type B = typeof(B);
        public readonly static Type Base = typeof(Base);
        public readonly static Type Basefont = typeof(Basefont);
        public readonly static Type Bdi = typeof(Bdi);
        public readonly static Type Bdo = typeof(Bdo);
        public readonly static Type Big = typeof(Big);
        public readonly static Type Blockquote = typeof(Blockquote);
        public readonly static Type Body = typeof(Body);
        public readonly static Type Br = typeof(Br);
        public readonly static Type Button = typeof(Button);
        public readonly static Type Canvas = typeof(Canvas);
        public readonly static Type Caption = typeof(Caption);
        public readonly static Type Center = typeof(Center);
        public readonly static Type Cite = typeof(Cite);
        public readonly static Type Code = typeof(Code);
        public readonly static Type Col = typeof(Col);
        public readonly static Type Colgroup = typeof(Colgroup);
        public readonly static Type Command = typeof(Command);
        public readonly static Type Datalist = typeof(Datalist);
        public readonly static Type Dd = typeof(Dd);
        public readonly static Type Del = typeof(Del);
        public readonly static Type Details = typeof(Details);
        public readonly static Type Dfn = typeof(Dfn);
        public readonly static Type Dialog = typeof(Dialog);
        public readonly static Type Dir = typeof(Dir);
        public readonly static Type Div = typeof(Div);
        public readonly static Type Dl = typeof(Dl);
        public readonly static Type Dt = typeof(Dt);
        public readonly static Type Em = typeof(Em);
        public readonly static Type Embed = typeof(Embed);
        public readonly static Type Fieldset = typeof(Fieldset);
        public readonly static Type Figcaption = typeof(Figcaption);
        public readonly static Type Figure = typeof(Figure);
        public readonly static Type Font = typeof(Font);
        public readonly static Type Footer = typeof(Footer);
        public readonly static Type Form = typeof(Form);
        public readonly static Type Frame = typeof(Frame);
        public readonly static Type Frameset = typeof(Frameset);
        public readonly static Type H1 = typeof(H1);
        public readonly static Type H2 = typeof(H2);
        public readonly static Type H3 = typeof(H3);
        public readonly static Type H4 = typeof(H4);
        public readonly static Type H5 = typeof(H5);
        public readonly static Type H6 = typeof(H6);
        public readonly static Type Head = typeof(Head);
        public readonly static Type Header = typeof(Header);
        public readonly static Type Hr = typeof(Hr);
        public readonly static Type Html = typeof(Html);
        public readonly static Type I = typeof(I);
        public readonly static Type Iframe = typeof(Iframe);
        public readonly static Type Img = typeof(Img);
        public readonly static Type Input = typeof(Input);
        public readonly static Type Ins = typeof(Ins);
        public readonly static Type Kbd = typeof(Kbd);
        public readonly static Type Keygen = typeof(Keygen);
        public readonly static Type Label = typeof(Label);
        public readonly static Type Legend = typeof(Legend);
        public readonly static Type Li = typeof(Li);
        public readonly static Type Link = typeof(Link);
        public readonly static Type Main = typeof(Main);
        public readonly static Type Map = typeof(Map);
        public readonly static Type Mark = typeof(Mark);
        public readonly static Type Menu = typeof(Menu);
        public readonly static Type Menuitem = typeof(Menuitem);
        public readonly static Type Meta = typeof(Meta);
        public readonly static Type Meter = typeof(Meter);
        public readonly static Type Nav = typeof(Nav);
        public readonly static Type Noframes = typeof(Noframes);
        public readonly static Type Noscript = typeof(Noscript);
        public readonly static Type Object = typeof(Object);
        public readonly static Type Ol = typeof(Ol);
        public readonly static Type Optgroup = typeof(Optgroup);
        public readonly static Type Option = typeof(Option);
        public readonly static Type Output = typeof(Output);
        public readonly static Type P = typeof(P);
        public readonly static Type Param = typeof(Param);
        public readonly static Type Pre = typeof(Pre);
        public readonly static Type Progress = typeof(Progress);
        public readonly static Type Q = typeof(Q);
        public readonly static Type Rp = typeof(Rp);
        public readonly static Type Rt = typeof(Rt);
        public readonly static Type Ruby = typeof(Ruby);
        public readonly static Type S = typeof(S);
        public readonly static Type Samp = typeof(Samp);
        public readonly static Type Script = typeof(Script);
        public readonly static Type Section = typeof(Section);
        public readonly static Type Select = typeof(Select);
        public readonly static Type Small = typeof(Small);
        public readonly static Type Source = typeof(Source);
        public readonly static Type Span = typeof(Span);
        public readonly static Type Strike = typeof(Strike);
        public readonly static Type Strong = typeof(Strong);
        public readonly static Type Style = typeof(Style);
        public readonly static Type Sub = typeof(Sub);
        public readonly static Type Summary = typeof(Summary);
        public readonly static Type Sup = typeof(Sup);
        public readonly static Type Table = typeof(Table);
        public readonly static Type Tbody = typeof(Tbody);
        public readonly static Type Td = typeof(Td);
        public readonly static Type Textarea = typeof(Textarea);
        public readonly static Type Tfoot = typeof(Tfoot);
        public readonly static Type Th = typeof(Th);
        public readonly static Type Thead = typeof(Thead);
        public readonly static Type Time = typeof(Time);
        public readonly static Type Title = typeof(Title);
        public readonly static Type Tr = typeof(Tr);
        public readonly static Type Track = typeof(Track);
        public readonly static Type Tt = typeof(Tt);
        public readonly static Type U = typeof(U);
        public readonly static Type Ul = typeof(Ul);
        public readonly static Type Var = typeof(Var);
        public readonly static Type Video = typeof(Video);
        public readonly static Type Wbr = typeof(Wbr);
    }
}
